name: Call Main Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      call-message:
        description: Optional override for the message sent to main-repo.
        required: false
        default: ""

jobs:
  invoke-reusable:
    uses: jokarl/main-repo/.github/workflows/reusable.yml@main
    with:
      caller-message: ${{ github.event.inputs['call-message'] != '' && github.event.inputs['call-message'] || vars.DEPENDANT_PUBLIC_MESSAGE }}
      caller-variable: ${{ vars.DEPENDANT_CONTEXT_NOTE }}
    secrets:
      caller-shared-secret: ${{ secrets.DEPENDANT_SECRET_FOR_MAIN }}
